### ISSUE TITLE
Redirect from bigbeastishank.com => www.bigbeastishank.com or vice versa

### ISSUE THREAD

**Issue by GoogolGenius** [BIGBEASTISHANK/bigbeastishank.com#2]
Small thing but it would probably be better to have a redirect between the www. and non www. versions of the website URL, instead of being deployed to two different URLs.

**Comment by GoogolGenius** [comment]
I noticed that it was implemented recently! Closing this issue...

**Comment by BIGBEASTISHANK** [comment]
Lol bro I never got any email regarding this issue, I was just going throught my repo and saw this. Damn, btw the update is I removed www part.
